name: Homestore Merge Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04", "ubuntu-20.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        prerelease: ["True", "False"]
        exclude:
          - build-type: Debug
            platform: ubuntu-20.04
          - build-type: Debug
            malloc-impl: tcmalloc
          - malloc-impl: tcmalloc
            platform: ubuntu-20.04
          - malloc-impl: jemalloc
            platform: ubuntu-20.04
          - malloc-impl: jemalloc
            build-type: Debug
          - malloc-impl: jemalloc
            prerelease: "False"
          - malloc-impl: libc
            build-type: Release
            platform: ubuntu-22.04
          - prerelease: "True"
            platform: ubuntu-20.04
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: ${{ matrix.platform }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
